### Unpackerr docker-compose.yml Example
### See this URL for variable descriptions and options:
### https://unpackerr.zip/docs/install/configuration
##################################################################
version: "3.7"
services:

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr-stack
    volumes:
      # You need at least this one volume mapped so Unpackerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - /volume1/docker/qbit/data/complete:/downloads
    restart: unless-stopped
    # Get the user:group correct so unpackerr can read and write to your files.
    user: 0:0
    #user: 1000:1000
    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    # Remove apps and feature configs you do not use or need. 
    # ie. Remove all lines that begin with UN_CMDHOOK, UN_WEBHOOK, UN_FOLDER, UN_WEBSERVER, and other apps you do not use.
    environment:
      - TZ=America/Los_Angeles
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=${SONAR_URL}
      - UN_SONARR_0_API_KEY=${SONAR_API}
      - UN_SONARR_0_PATHS_0=/downloads/tv-sonarr
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=${RADAR_URL}
      - UN_RADARR_0_API_KEY=${RADAR_API}
      - UN_RADARR_0_PATHS_0=/downloads/radarr
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Folder Config
      - UN_FOLDER_0_PATH=/downloads

    security_opt:
      - no-new-privileges:true