
version: "3.4"
services:
  requestrr:
    image: thomst08/requestrr
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - /volume1/docker/requestrr/config:/root/config
    restart: unless-stopped